// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ojcfkTN1Z86IiRT3zOjtPahvJYo7Vyc',
    appId: '1:747856476004:web:86429204ef3f4c74a36c71',
    messagingSenderId: '747856476004',
    projectId: 'voiceup-e695d',
    authDomain: 'voiceup-e695d.firebaseapp.com',
    storageBucket: 'voiceup-e695d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKB6MVA2Plo-zvfOFkTxHAni1X8t5RJOk',
    appId: '1:747856476004:android:9a390dbc785611d2a36c71',
    messagingSenderId: '747856476004',
    projectId: 'voiceup-e695d',
    storageBucket: 'voiceup-e695d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI3qtDHNGNchSohYSeN0NFBA1sosVHrfM',
    appId: '1:747856476004:ios:87e0fe635d7f84bda36c71',
    messagingSenderId: '747856476004',
    projectId: 'voiceup-e695d',
    storageBucket: 'voiceup-e695d.firebasestorage.app',
    iosBundleId: 'com.example.voiceup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI3qtDHNGNchSohYSeN0NFBA1sosVHrfM',
    appId: '1:747856476004:ios:87e0fe635d7f84bda36c71',
    messagingSenderId: '747856476004',
    projectId: 'voiceup-e695d',
    storageBucket: 'voiceup-e695d.firebasestorage.app',
    iosBundleId: 'com.example.voiceup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ojcfkTN1Z86IiRT3zOjtPahvJYo7Vyc',
    appId: '1:747856476004:web:9ceb4f247871def7a36c71',
    messagingSenderId: '747856476004',
    projectId: 'voiceup-e695d',
    authDomain: 'voiceup-e695d.firebaseapp.com',
    storageBucket: 'voiceup-e695d.firebasestorage.app',
  );

}